name: dr_score
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu118
      - torch==2.7.1+cu118
      - torchvision==0.22.1+cu118
      - -r requirements.txt
